#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@rstacruz/startup-name-generator/bin/startup-name-generator" "$@"
else 
  exec node  "$basedir/../@rstacruz/startup-name-generator/bin/startup-name-generator" "$@"
fi
